# This workflow will build python files to exe
# But only upload this file as artifacts
# This workflow and whole this branch created only for tests
# Please, don't download artifacts, it's not releases at all!

name: CI Tests

on:
  push:
    branches: [ CI-test ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install py2exe

    - name: Setup PyWin32
      run: python "$env:pythonLocation/Scripts/pywin32_postinstall.py" -install

    - name: Convert python files to exe using py2exe
      run: python setup.py py2exe

    - name: Compress files
      uses: vimtor/action-zip@v1
      with:
        files: dist/
        dest: test_results.zip

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: test_results
        path: ./test_results.zip
        retention-days: 1
